site_name: QualCoder
site_description: 'QualCoder Website'
site_author: 'QualCoder Teams'
edit_uri: edit/main/docs/
docs_dir: docs/
repo_name: 'QualCoder-Org/qualcoder-org.github.io'
repo_url: 'https://github.com/QualCoder-Org/qualcoder-org.github.io'

theme:
  name: 'material'
  custom_dir: overrides
  logo: images/logo.png
  favicon: images/logo.png
  lang: en
  palette:
    primary: deep purple
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - navigation.path
    - attr_list
    - content.action.edit
    - content.code.annotate
    - content.tabs.link
    - navigation.footer
  extra:
    extra_css:
    - stylesheets/extra.css
    alternate:
      - name: English
        link: /doc/en/
        lang: en
      - name: Français
        link: /doc/fr/
        lang: fr

plugins:
  - blog
  - rss
  - search

nav:
  - Home: index.md
  - Blog: blog/
  - Documentation:
      - English Documentation:
          - Overview: doc/en/index.md
          - Setup:
              - doc/en/2.1.-Installation.md
              - doc/en/2.2.-Settings.md
              - doc/en/2.3.-AI-Setup.md
              - doc/en/2.4.-Working-in-a-Team.md
          - Managing Data:
              - doc/en/3.1.-Creating-a-New-Project.md
              - doc/en/3.2.-Files.md
              - doc/en/3.3.-Cases.md
              - doc/en/3.4.-Attributes.md
          - Coding:
              - doc/en/4.1.-Coding-Text.md
              - doc/en/4.2.-AI-Assisted-Coding.md
              - doc/en/4.3.-Coding-Text-on-PDFs.md
              - doc/en/4.4.-Coding-Images.md
              - doc/en/4.5.-Coding-Audio-and-Video.md
              - doc/en/4.6-Code-Organiser.md
          - Analyzing the Results:
              - doc/en/5.1.-AI-chat-based-analysis.md
              - doc/en/5.2.-Journals.md
              - doc/en/5.3.-Reports.md
              - doc/en/5.4.-Graph.md
          - Advanced Options:
              - doc/en/6.1.-Imports-and-Exports.md
              - doc/en/6.2.-AI-Prompt-Library.md
          - Other Information:
              - doc/en/7.1.-About-The-Developers.md
              - doc/en/7.2.-QualCoder-Video-Tutorials.md
              - doc/en/7.3.-QualCoder-Development.md
              - doc/en/7.4.-SQlite-Data-Structure.md
              - doc/en/7.5.-AI-Technical-Information.md
      - Documentation en français:
          - Aperçu: doc/fr/index.md
          - Installation et configuration:
              - doc/fr/2.1.-Installation.md
              - doc/fr/2.2.-Settings.md
              - doc/fr/2.3.-AI-Setup.md
              - doc/fr/2.4.-Working-in-a-Team.md
          - Gestion des données:
              - doc/fr/3.1.-Creating-a-New-Project.md
              - Fichiers: doc/fr/3.2.-Files.md
              - Cas: doc/fr/3.3.-Cases.md
              - Attributs: doc/fr/3.4.-Attributes.md
          - Codage:
              - doc/fr/4.1.-Coding-Text.md
              - doc/fr/4.2.-AI-Assisted-Coding.md
              - doc/fr/4.3.-Coding-Text-on-PDFs.md
              - doc/fr/4.4.-Coding-Images.md
              - doc/fr/4.5.-Coding-Audio-and-Video.md
              - doc/fr/4.6-Code-Organiser.md
          - Analyser les résultats:
              - doc/fr/5.1.-AI-chat-based-analysis.md
              - doc/fr/5.2.-Journals.md
              - doc/fr/5.3.-Reports.md
              - doc/fr/5.4.-Graph.md
          - Options avancées:
              - doc/fr/6.1.-Imports-and-Exports.md
              - doc/fr/6.2.-AI-Prompt-Library.md
          - Autres informations:
              - doc/fr/7.1.-About-The-Developers.md
              - doc/fr/7.2.-QualCoder-Video-Tutorials.md
              - doc/fr/7.3.-QualCoder-Development.md
              - doc/fr/7.4.-SQlite-Data-Structure.md
              - doc/fr/7.5.-AI-Technical-Information.md
              - doc/fr/Translation.md
  - Resources: ressources.md
  - 'Studies using QualCoder': using.md
  - 'About Developers': about.md
  - 'Forum': 'https://github.com/ccbogel/QualCoder/discussions'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ccbogel/QualCoder
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/1251478525589873

