site_name: QualCoder
site_description: 'QualCoder Website'
site_author: 'QualCoder Teams'
docs_dir: docs/
repo_name: 'QualCoder-Org/qualcoder-org.github.io'
repo_url: 'https://github.com/QualCoder-Org/qualcoder-org.github.io'
nav:
    - Home: index.md
theme:
  name: 'material'
