site_name: QualCoder
site_description: 'QualCoder Website'
site_author: 'QualCoder Teams'
edit_uri: edit/main/docs/
docs_dir: docs/
repo_name: 'QualCoder-Org/qualcoder-org.github.io'
repo_url: 'https://github.com/QualCoder-Org/qualcoder-org.github.io'
theme:
  name: 'material'
  logo: images/logo.png
  favicon: images/logo.png
  palette:
    primary: deep purple
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 


      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - attr_list
    - content.action.edit
    - content.code.annotate
    - content.tabs.link
    - navigation.footer
plugins:
  - blog
nav:
  - Home: index.md
  - Blog: blog/
  - Documentation:
      - English:
          - Documentation: doc/en/index.md
          - 'Setup':
              - 'Installation': 'doc/en/2.1.-Installation.md'
              - 'Settings': 'doc/en/2.2.-Settings.md'
              - 'AI Setup': 'doc/en/2.3.-AI-Setup.md'
              - 'Working in a Team': 'doc/en/2.4.-Working-in-a-Team.md'
          - 'Managing Data':
              - 'Creating a New Project': 'doc/en/3.1.-Creating-a-New-Project.md'
              - 'Files': 'doc/en/3.2.-Files.md'
              - 'Cases': 'doc/en/3.3.-Cases.md'
              - 'Attributes': 'doc/en/3.4.-Attributes.md'
          - 'Coding':
              - 'Coding Text': 'doc/en/4.1.-Coding-Text.md'
              - 'AI-Assisted Coding': 'doc/en/4.2.-AI-Assisted-Coding.md'
              - 'Coding Text on PDFs': 'doc/en/4.3.-Coding-Text-on-PDFs.md'
              - 'Coding Images': 'doc/en/4.4.-Coding-Images.md'
              - 'Coding Audio and Video': 'doc/en/4.5.-Coding-Audio-and-Video.md'
              - 'Code Organiser': 'doc/en/4.6-Code-Organiser.md'
          - 'Analyzing the Results':
              - 'AI Chat-based Analysis': 'doc/en/5.1.-AI-chat-based-analysis.md'
              - 'Journals': 'doc/en/5.2.-Journals.md'
              - 'Reports': 'doc/en/5.3.-Reports.md'
              - 'Graph': 'doc/en/5.4.-Graph.md'
          - 'Advanced Options':
              - 'Imports and Exports': 'doc/en/6.1.-Imports-and-Exports.md'
              - 'AI Prompt Library': 'doc/en/6.2.-AI-Prompt-Library.md'
          - 'Others informations':
              - 'About The Developers': 'doc/en/7.1.-About-The-Developers.md'
              - 'QualCoder Video Tutorials': 'doc/en/7.2.-QualCoder-Video-Tutorials.md'
              - 'QualCoder Development': 'doc/en/7.3.-QualCoder-Development.md'
              - 'SQLite Data Structure': 'doc/en/7.4.-SQlite-Data-Structure.md'
              - 'AI Technical Information': 'doc/en/7.5.-AI-Technical-Information.md'
      - Français:
          - Documentation: doc/fr/index.md
          - 'Installation et configuration':
              - 'Installation': 'doc/fr/2.1.-Installation.md'
              - 'Settings': 'doc/fr/2.2.-Settings.md'
              - 'AI Setup': 'doc/fr/2.3.-AI-Setup.md'
              - 'Working in a Team': 'doc/fr/2.4.-Working-in-a-Team.md'
          - 'Gestion des données':
              - 'Creating a New Project': 'doc/fr/3.1.-Creating-a-New-Project.md'
              - 'Files': 'doc/fr/3.2.-Files.md'
              - 'Cases': 'doc/fr/3.3.-Cases.md'
              - 'Attributes': 'doc/fr/3.4.-Attributes.md'
          - 'Codage':
              - 'Coding Text': 'doc/fr/4.1.-Coding-Text.md'
              - 'AI-Assisted Coding': 'doc/fr/4.2.-AI-Assisted-Coding.md'
              - 'Coding Text on PDFs': 'doc/fr/4.3.-Coding-Text-on-PDFs.md'
              - 'Coding Images': 'doc/fr/4.4.-Coding-Images.md'
              - 'Coding Audio and Video': 'doc/fr/4.5.-Coding-Audio-and-Video.md'
              - 'Code Organiser': 'doc/fr/4.6-Code-Organiser.md'
          - 'Analyser les résultats':
              - 'AI Chat-based Analysis': 'doc/fr/5.1.-AI-chat-based-analysis.md'
              - 'Journals': 'doc/fr/5.2.-Journals.md'
              - 'Reports': 'doc/fr/5.3.-Reports.md'
              - 'Graph': 'doc/fr/5.4.-Graph.md'
          - 'Options avancées':
              - 'Imports and Exports': 'doc/fr/6.1.-Imports-and-Exports.md'
              - 'AI Prompt Library': 'doc/fr/6.2.-AI-Prompt-Library.md'
          - 'Autres informations':
              - 'About The Developers': 'doc/fr/7.1.-About-The-Developers.md'
              - 'QualCoder Video Tutorials': 'doc/fr/7.2.-QualCoder-Video-Tutorials.md'
              - 'QualCoder Development': 'doc/fr/7.3.-QualCoder-Development.md'
              - 'SQLite Data Structure': 'doc/fr/7.4.-SQlite-Data-Structure.md'
              - 'AI Technical Information': 'doc/fr/7.5.-AI-Technical-Information.md'
  - 'Ressources': ressources.md
  - 'Studies using QualCoder': using.md
  - 'About Developers': about.md



extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ccbogel/QualCoder
alternate:
  - name: English
    link: /
    lang: en
  - name: Deutsch
    link: /de/
    lang: de
  - name: Français
    link: /fr/
    lang: fr
  - name: Español
    link: /es/
    lang: es
  - name: Italiano
    link: /it/
    lang: it
  - name: 日本語
    link: /ja/
    lang: ja
  - name: Português
    link: /pt/
    lang: pt
  - name: Svenska
    link: /sv/
    lang: sv
  - name: 中文
    link: /zh/
    lang: zh


