site_name: QualCoder
site_description: 'QualCoder Website'
site_author: 'QualCoder Teams'
edit_uri: edit/main/docs/
docs_dir: docs/
repo_name: 'QualCoder-Org/qualcoder-org.github.io'
repo_url: 'https://github.com/QualCoder-Org/qualcoder-org.github.io'
plugins:
  - blog
  
nav:
    - Home: index.md
    - News: news/index.md
    - Documentation : doc.md
          - 'English':
              - doc/en/index.md
              - 'Installation et configuration':
                  - 'doc/en/2.1.-Installation.md'
                  - 'doc/en/2.2.-Settings.md'
                  - 'doc/en/2.3.-AI-Setup.md'
                  - 'doc/en/2.4.-Working-in-a-Team.md'
              - 'Gestion des données':
                  - 'doc/en/3.1.-Creating-a-New-Project.md'
                  - 'doc/en/3.2.-Files.md'
                  - 'doc/en/3.3.-Cases.md'
                  - 'doc/en/3.4.-Attributes.md'
              - 'Codage':
                  - 'doc/en/4.1.-Coding-Text.md'
                  - 'doc/en/4.2.-AI-Assisted-Coding.md'
                  - 'doc/en/4.3.-Coding-Text-on-PDFs.md'
                  - 'doc/en/4.4.-Coding-Images.md'
                  - 'doc/en/4.5.-Coding-Audio-and-Video.md'
                  - 'doc/en/4.6-Code-Organiser.md'
              - 'Analyser les résultats':
                  - 'doc/en/5.1.-AI-chat-based-analysis.md'
                  - 'doc/en/5.2.-Journals.md'
                  - 'doc/en/5.3.-Reports.md'
                  - 'doc/en/5.4.-Graph.md'
              - 'Options avancées':
                  - 'doc/en/6.1.-Imports-and-Exports.md'
                  - 'doc/en/6.2.-AI-Prompt-Library.md'
              - 'Autres informations':
                  - 'doc/en/7.1.-About-The-Developers.md'
                  - 'doc/en/7.2.-QualCoder-Video-Tutorials.md'
                  - 'doc/en/7.3.-QualCoder-Development.md'
                  - 'doc/en/7.4.-SQlite-Data-Structure.md'
                  - 'doc/en/7.5.-AI-Technical-Information.md'
    
    - 'Studies using QualCoder': using.md
    - 'About Developers': about.md
theme:
  name: 'material'
  logo: images/logo.png
  favicon: images/logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - attr_list
    - content.action.edit
    - content.code.annotate
    - content.tabs.link
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/ccbogel/QualCoder

extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Deutsch
      link: /de/
      lang: de
    - name: Français
      link: /fr/
      lang: fr
    - name: Spanish
      link: /es/
      lang: es
    - name: Italian
      link: /it/
      lang: it
    - name: Japanese
      link: /ja/
      lang: ja
    - name: Portugese
      link: /pt/
      lang: pt
    - name: Swedish
      link: /sv/
      lang: sv
    - name: Chinese
      link: /zh/
      lang: zh
