site_name: QualCoder
site_description: 'QualCoder Website'
site_author: 'QualCoder Teams'
edit_uri: edit/main/docs/
docs_dir: docs/
repo_name: 'QualCoder-Org/qualcoder-org.github.io'
repo_url: 'https://github.com/QualCoder-Org/qualcoder-org.github.io'
theme:
  name: 'material'
  logo: images/logo.png
  favicon: images/logo.png
  lang: en
  palette:
    primary: deep purple
  extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Français
      link: /fr/
      lang: fr
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - navigation.path
    - attr_list
    - content.action.edit
    - content.code.annotate
    - content.tabs.link
    - navigation.footer
plugins:
  - blog
  - rss
  - search
nav:
  - en:
    - Home: index.md
    - Blog: /blog/
    - Documentation:
      - Overview: en/doc/index.md
      - 'Setup':
          - 'en/doc/2.1.-Installation.md'
          - 'en/doc/2.2.-Settings.md'
          - 'en/doc/2.3.-AI-Setup.md'
          - 'en/doc/2.4.-Working-in-a-Team.md'
      - 'Managing Data':
          - 'en/doc/3.1.-Creating-a-New-Project.md'
          - 'en/doc/3.2.-Files.md'
          - 'en/doc/3.3.-Cases.md'
          - 'en/doc/3.4.-Attributes.md'
      - 'Coding':
          - 'en/doc/4.1.-Coding-Text.md'
          - 'en/doc/4.2.-AI-Assisted-Coding.md'
          - 'en/doc/4.3.-Coding-Text-on-PDFs.md'
          - 'en/doc/4.4.-Coding-Images.md'
          - 'en/doc/4.5.-Coding-Audio-and-Video.md'
          - 'en/doc/4.6-Code-Organiser.md'
      - 'Analyzing the Results':
          - 'en/doc/5.1.-AI-chat-based-analysis.md'
          - 'en/doc/5.2.-Journals.md'
          - 'en/doc/5.3.-Reports.md'
          - 'en/doc/5.4.-Graph.md'
      - 'Advanced Options':
          - 'en/doc/6.1.-Imports-and-Exports.md'
          - 'en/doc/6.2.-AI-Prompt-Library.md'
      - 'Other information':
          - 'en/doc/7.1.-About-The-Developers.md'
          - 'en/doc/7.2.-QualCoder-Video-Tutorials.md'
          - 'en/doc/7.3.-QualCoder-Development.md'
          - 'en/doc/7.4.-SQlite-Data-Structure.md'
          - 'en/doc/7.5.-AI-Technical-Information.md'
    - 'Resources': en/ressources.md
    - 'Studies using QualCoder': en/using.md
    - 'About Developers': en/about.md
    - 'Forum': 'https://github.com/ccbogel/QualCoder/discussions'
  - fr:
    - Home: index.md
    - Blog: /blog/
    - Documentation:
      - Aperçu: fr/doc/index.md
      - 'Installation et configuration':
          - 'fr/doc/2.1.-Installation.md'
          - 'fr/doc/2.2.-Settings.md'
          - 'fr/doc/2.3.-AI-Setup.md'
          - 'fr/doc/2.4.-Working-in-a-Team.md'
      - 'Gestion des données':
          - 'fr/doc/3.1.-Creating-a-New-Project.md'
          - 'fr/doc/3.2.-Files.md'
          - 'fr/doc/3.3.-Cases.md'
          - 'fr/doc/3.4.-Attributes.md'
      - 'Codage':
          - 'fr/doc/4.1.-Coding-Text.md'
          - 'fr/doc/4.2.-AI-Assisted-Coding.md'
          - 'fr/doc/4.3.-Coding-Text-on-PDFs.md'
          - 'fr/doc/4.4.-Coding-Images.md'
          - 'fr/doc/4.5.-Coding-Audio-and-Video.md'
          - 'fr/doc/4.6-Code-Organiser.md'
      - 'Analyser les résultats':
          - 'fr/doc/5.1.-AI-chat-based-analysis.md'
          - 'fr/doc/5.2.-Journals.md'
          - 'fr/doc/5.3.-Reports.md'
          - 'fr/doc/5.4.-Graph.md'
      - 'Options avancées':
          - 'fr/doc/6.1.-Imports-and-Exports.md'
          - 'fr/doc/6.2.-AI-Prompt-Library.md'
      - 'Autres informations':
          - 'fr/doc/7.1.-About-The-Developers.md'
          - 'fr/doc/7.2.-QualCoder-Video-Tutorials.md'
          - 'fr/doc/7.3.-QualCoder-Development.md'
          - 'fr/doc/7.4.-SQlite-Data-Structure.md'
          - 'fr/doc/7.5.-AI-Technical-Information.md'
          - 'fr/doc/Translation.md'
    - 'Ressources': fr/ressources.md
    - 'Études utilisant QualCoder': fr/using.md
    - 'Équipe de développement': fr/about.md
    - 'Forum': 'https://github.com/ccbogel/QualCoder/discussions'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ccbogel/QualCoder
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/1251478525589873
