site_name: QualCoder
site_description: 'QualCoder Website'
site_author: 'QualCoder Teams'
docs_dir: docs/
repo_name: 'QualCoder-Org/qualcoder-org.github.io'
repo_url: 'https://github.com/QualCoder-Org/qualcoder-org.github.io'
nav:
    - Home: index.md
theme:
  name: 'material'
  logo: images/logo.png
  favicon: images/logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - attr_list
    - content.action.edit
    - content.code.annotate
    - content.tabs.link
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/ccbogel/QualCoder
extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Deutsch
      link: /de/
      lang: de
  lang: fr
    - name: Fran√ßais
      link: /fr/
      lang: fr
  lang: es
    - name: Spanish
      link: /es/
      lang: es
  lang: it
    - name: Italian
      link: /it/
      lang: it
  lang: ja
    - name: Japanese
      link: /ja/
      lang: ja
  lang: pt
    - name: Portugese
      link: /pt/
      lang: pt
  lang: sv
    - name: Swedish
      link: /sv/
      lang: sv
  lang: zh
    - name: Chinese
      link: /zh/
      lang: zh
